[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::langchain_core._api.deprecation.LangChainDeprecationWarning
    ignore::FutureWarning:google.api_core.*
    ignore::FutureWarning:langchain_google_genai.*